"""001_initial_schema

Revision ID: 17988d790c82
Revises: 
Create Date: 2026-08-22 17:20:01.494944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17988d790c82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('total_triggered', sa.Integer(), nullable=True),
    sa.Column('total_overridden', sa.Integer(), nullable=True),
    sa.Column('total_accepted', sa.Integer(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id')
    )
    op.create_index(op.f('ix_alert_metrics_id'), 'alert_metrics', ['id'], unique=False)
    op.create_table('amr_surveillance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('organism', sa.String(length=128), nullable=False),
    sa.Column('antimicrobial', sa.String(length=128), nullable=False),
    sa.Column('resistance_rate_pct', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('geographic_scope', sa.String(length=128), nullable=False),
    sa.Column('data_source', sa.String(length=256), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amr_surveillance_records_id'), 'amr_surveillance_records', ['id'], unique=False)
    op.create_index(op.f('ix_amr_surveillance_records_record_id'), 'amr_surveillance_records', ['record_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('prescription_id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('clinician_id', sa.String(length=64), nullable=False),
    sa.Column('clinician_role', sa.String(length=64), nullable=False),
    sa.Column('action_summary', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('integrity_hash', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_template_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_log_id'), 'audit_logs', ['log_id'], unique=True)
    op.create_table('clinical_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_conditions_json', sa.Text(), nullable=False),
    sa.Column('output_concern', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('evidence_source', sa.String(length=256), nullable=False),
    sa.Column('guideline_version', sa.String(length=64), nullable=False),
    sa.Column('effective_date', sa.String(length=32), nullable=True),
    sa.Column('review_date', sa.String(length=32), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('approval_status', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('section_page', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_rules_id'), 'clinical_rules', ['id'], unique=False)
    op.create_index(op.f('ix_clinical_rules_rule_id'), 'clinical_rules', ['rule_id'], unique=True)
    op.create_table('guideline_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('issuing_org', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('geographic_scope', sa.String(length=128), nullable=False),
    sa.Column('precedence_rank', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('document_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guideline_documents_document_id'), 'guideline_documents', ['document_id'], unique=True)
    op.create_index(op.f('ix_guideline_documents_id'), 'guideline_documents', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('age_category', sa.String(length=32), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('allergies_json', sa.Text(), nullable=True),
    sa.Column('allergy_status_known', sa.Boolean(), nullable=True),
    sa.Column('egfr_ml_min', sa.Float(), nullable=True),
    sa.Column('serum_creatinine_mg_dl', sa.Float(), nullable=True),
    sa.Column('renal_status_known', sa.Boolean(), nullable=True),
    sa.Column('child_pugh_class', sa.String(length=8), nullable=True),
    sa.Column('hepatic_status_known', sa.Boolean(), nullable=True),
    sa.Column('pregnancy_status', sa.String(length=32), nullable=True),
    sa.Column('lactation_status', sa.String(length=32), nullable=True),
    sa.Column('active_medications_json', sa.Text(), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=True)
    op.create_table('rule_authorship_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('author_id', sa.String(length=64), nullable=False),
    sa.Column('author_role', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_authorship_logs_id'), 'rule_authorship_logs', ['id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('diagnosis', sa.String(length=256), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('clinician_id', sa.String(length=64), nullable=True),
    sa.Column('clinician_role', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=False)
    op.create_index(op.f('ix_prescriptions_prescription_id'), 'prescriptions', ['prescription_id'], unique=True)
    op.create_table('prescription_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.String(length=64), nullable=False),
    sa.Column('medication_name', sa.String(length=128), nullable=False),
    sa.Column('dose', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('route', sa.String(length=32), nullable=True),
    sa.Column('frequency', sa.String(length=32), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('indication', sa.String(length=256), nullable=True),
    sa.Column('antimicrobial_class', sa.String(length=64), nullable=True),
    sa.Column('aware_category', sa.String(length=32), nullable=True),
    sa.Column('extraction_confidence_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.prescription_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_items_id'), 'prescription_items', ['id'], unique=False)
    op.create_table('safety_warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warning_id', sa.String(length=128), nullable=False),
    sa.Column('prescription_id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('clinical_concern', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('prescribed_drug', sa.String(length=128), nullable=False),
    sa.Column('interacting_factor', sa.String(length=128), nullable=True),
    sa.Column('evidence_document', sa.String(length=256), nullable=False),
    sa.Column('evidence_version', sa.String(length=64), nullable=False),
    sa.Column('evidence_passage', sa.Text(), nullable=False),
    sa.Column('evidence_url', sa.String(length=512), nullable=True),
    sa.Column('supporting_labels_json', sa.Text(), nullable=True),
    sa.Column('rule_author', sa.String(length=128), nullable=True),
    sa.Column('rule_approval_status', sa.String(length=128), nullable=True),
    sa.Column('rule_effective_date', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.prescription_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_warnings_id'), 'safety_warnings', ['id'], unique=False)
    op.create_index(op.f('ix_safety_warnings_warning_id'), 'safety_warnings', ['warning_id'], unique=True)
    op.create_table('clinician_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('override_id', sa.String(length=64), nullable=False),
    sa.Column('warning_id', sa.String(length=64), nullable=False),
    sa.Column('prescription_id', sa.String(length=64), nullable=False),
    sa.Column('clinician_id', sa.String(length=64), nullable=False),
    sa.Column('clinician_role', sa.String(length=64), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['warning_id'], ['safety_warnings.warning_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinician_overrides_id'), 'clinician_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_clinician_overrides_override_id'), 'clinician_overrides', ['override_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinician_overrides_override_id'), table_name='clinician_overrides')
    op.drop_index(op.f('ix_clinician_overrides_id'), table_name='clinician_overrides')
    op.drop_table('clinician_overrides')
    op.drop_index(op.f('ix_safety_warnings_warning_id'), table_name='safety_warnings')
    op.drop_index(op.f('ix_safety_warnings_id'), table_name='safety_warnings')
    op.drop_table('safety_warnings')
    op.drop_index(op.f('ix_prescription_items_id'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('ix_prescriptions_prescription_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_rule_authorship_logs_id'), table_name='rule_authorship_logs')
    op.drop_table('rule_authorship_logs')
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_guideline_documents_id'), table_name='guideline_documents')
    op.drop_index(op.f('ix_guideline_documents_document_id'), table_name='guideline_documents')
    op.drop_table('guideline_documents')
    op.drop_index(op.f('ix_clinical_rules_rule_id'), table_name='clinical_rules')
    op.drop_index(op.f('ix_clinical_rules_id'), table_name='clinical_rules')
    op.drop_table('clinical_rules')
    op.drop_index(op.f('ix_audit_logs_log_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_amr_surveillance_records_record_id'), table_name='amr_surveillance_records')
    op.drop_index(op.f('ix_amr_surveillance_records_id'), table_name='amr_surveillance_records')
    op.drop_table('amr_surveillance_records')
    op.drop_index(op.f('ix_alert_metrics_id'), table_name='alert_metrics')
    op.drop_table('alert_metrics')
    # ### end Alembic commands ###
